version: 2

project_name: wacli-readonly

builds:
  - id: wacli-readonly
    main: ./cmd/wacli
    binary: wacli-readonly
    env:
      - CGO_ENABLED=1
    flags:
      - -trimpath
    tags:
      - sqlite_fts5
    ldflags:
      - -s -w -X main.version={{.Version}}
    goos:
      - darwin
    goarch:
      - amd64
      - arm64

universal_binaries:
  - id: wacli-readonly
    ids:
      - wacli-readonly
    name_template: wacli-readonly
    replace: true

archives:
  - id: default
    format: tar.gz
    name_template: >-
      {{ .ProjectName }}-{{ if eq .Os "darwin" }}macos{{ else }}{{ .Os }}{{ end }}-{{ if eq .Arch "all" }}universal{{ else }}{{ .Arch }}{{ end }}
    files:
      - LICENSE
      - README.md

checksum:
  name_template: checksums.txt

brews:
  - name: wacli-readonly
    directory: Formula
    repository:
      owner: regalstreak
      name: homebrew-tap
      token: "{{ .Env.HOMEBREW_TAP_GITHUB_TOKEN }}"
    homepage: "https://github.com/regalstreak/wacli-readonly"
    description: "Read-only WhatsApp CLI for syncing and searching messages"
    license: "MIT"
    install: |
      bin.install "wacli-readonly"

changelog:
  sort: asc
  filters:
    exclude:
      - "^docs:"
      - "^test:"
      - "^chore:"
